apiVersion: v1
kind: Service
metadata:
  name: net-reply-service
spec:
  ports:
    - name: http
      port: 8081
      targetPort: http
    - name: grpc
      port: 8080
      targetPort: grpc
  selector:
    app: net-reply
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-reply-grpc
  labels:
    app: net-reply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-reply
  template:
    metadata:
      labels:
        app: net-reply
    spec:
      containers:
        - name: net-reply-grpc-container
          image: jamesmilligan/net-reply-grpc
          ports:
            - name: grpc
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-reply-rest
  labels:
    app: net-reply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-reply
  template:
    metadata:
      labels:
        app: net-reply
    spec:
      containers:
        - name: net-reply-rest-container
          image: jamesmilligan/net-reply-rest
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: GRPC_NETWORK_ADDRESS
              value: "net-reply-service"
