apiVersion: v1
kind: Service
metadata:
  name: net-reply-service
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 8080
      targetPort: 8080
  selector:
    app: net-reply
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-reply-grpc
  labels:
    app: net-reply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-reply
  template:
    metadata:
      labels:
        app: net-reply
    spec:
      containers:
        - name: net-reply-grpc-container
          image: jamesmilligan/net-reply-grpc
          ports:
            - containerPort: 8080
          env:
            - name: GRPC_SERVER_PORT
              value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-reply-rest
  labels:
    app: net-reply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-reply
  template:
    metadata:
      labels:
        app: net-reply
    spec:
      containers:
        - name: net-reply-rest-container
          image: jamesmilligan/net-reply-rest
          ports:
            - containerPort: 8081
          env:
            - name: GRPC_SERVER_PORT
              value: "8080"
            - name: GRPC_NETWORK_ADDRESS
              value: "net-reply-service"
            - name: REST_SERVER_PORT
              value: "8081"
